import type { Application, Client, Document, Template, ActivityItem, Notification } from './types'

export const APPLICATIONS: Application[] = [
  {
    id: 'invoice',
    name: 'Invoice Automation',
    description: 'Generate professional GST invoices with automated calculations and payment tracking.',
    icon: 'Receipt',
    color: '#2563EB',
    gradient: 'from-blue-500 to-blue-700',
    category: 'Finance',
  },
  {
    id: 'offer-letter',
    name: 'Offer Letter Generator',
    description: 'Create legally sound offer letters with customizable compensation structures.',
    icon: 'FileText',
    color: '#059669',
    gradient: 'from-emerald-500 to-emerald-700',
    category: 'HR',
  },
  {
    id: 'hr-documents',
    name: 'HR Documents',
    description: 'Automate all HR documentation from onboarding to exit formalities.',
    icon: 'Users',
    color: '#7C3AED',
    gradient: 'from-violet-500 to-violet-700',
    category: 'HR',
  },
  {
    id: 'question-generator',
    name: 'Question Generator',
    description: 'Generate exam papers, quizzes, and assessments with AI assistance.',
    icon: 'HelpCircle',
    color: '#D97706',
    gradient: 'from-amber-500 to-orange-600',
    category: 'Education',
  },
  {
    id: 'certificates',
    name: 'Certificates',
    description: 'Design and generate professional certificates for courses, achievements, and events.',
    icon: 'Award',
    color: '#DC2626',
    gradient: 'from-rose-500 to-red-600',
    category: 'Education',
  },
  {
    id: 'resume-builder',
    name: 'Resume Builder',
    description: 'Build ATS-friendly resumes with professional templates and AI suggestions.',
    icon: 'UserCircle',
    color: '#0891B2',
    gradient: 'from-cyan-500 to-cyan-700',
    category: 'Career',
  },
  {
    id: 'resume-analyzer',
    name: 'Resume Analyzer',
    description: 'Analyze and score resumes against job descriptions with detailed feedback.',
    icon: 'BarChart2',
    color: '#6366F1',
    gradient: 'from-indigo-500 to-indigo-700',
    category: 'Career',
  },
  {
    id: 'experience-letter',
    name: 'Experience Letter',
    description: 'Generate experience letters with accurate employment details and company letterhead.',
    icon: 'Briefcase',
    color: '#0D9488',
    gradient: 'from-teal-500 to-teal-700',
    category: 'HR',
  },
  {
    id: 'appointment-letter',
    name: 'Appointment Letter',
    description: 'Create formal appointment letters with roles, responsibilities, and joining details.',
    icon: 'ClipboardList',
    color: '#EA580C',
    gradient: 'from-orange-500 to-orange-700',
    category: 'HR',
  },
  {
    id: 'salary-slip',
    name: 'Salary Slip',
    description: 'Automate monthly salary slip generation with earnings, deductions, and tax details.',
    icon: 'Banknote',
    color: '#16A34A',
    gradient: 'from-green-500 to-green-700',
    category: 'Finance',
  },
  {
    id: 'id-card',
    name: 'ID Card Generator',
    description: 'Design and generate professional employee and student ID cards.',
    icon: 'CreditCard',
    color: '#9333EA',
    gradient: 'from-purple-500 to-purple-700',
    category: 'Design',
  },
]

export const CLIENTS: Client[] = [
  { id: '1', company: 'TechNova Solutions', contactPerson: 'Arjun Sharma', email: 'arjun@technova.in', phone: '+91 98765 43210', gstNumber: '27AAPCA1234B1Z1', address: '42 Tech Park, Whitefield', city: 'Bengaluru', country: 'India', postalCode: '560066', paymentTerms: 'Net 30', notes: 'Premium client, priority support', logo: 'TN', documentsCount: 24, status: 'active', revenue: 480000, createdAt: '2024-01-15' },
  { id: '2', company: 'GlobalEdge Consulting', contactPerson: 'Priya Nair', email: 'priya@globaledge.com', phone: '+91 87654 32109', gstNumber: '07AABCG5678C2Z2', address: '15 Cyber City, DLF Phase 3', city: 'Gurugram', country: 'India', postalCode: '122002', paymentTerms: 'Net 15', notes: 'Consulting firm, bulk orders', logo: 'GE', documentsCount: 18, status: 'active', revenue: 320000, createdAt: '2024-02-01' },
  { id: '3', company: 'SkyBuild Infra', contactPerson: 'Rohan Mehta', email: 'rohan@skybuild.co', phone: '+91 76543 21098', gstNumber: '24AADCS3456D3Z3', address: '7 Construction House, Satellite', city: 'Ahmedabad', country: 'India', postalCode: '380015', paymentTerms: 'Net 45', notes: 'Large infrastructure company', logo: 'SB', documentsCount: 31, status: 'active', revenue: 750000, createdAt: '2023-11-20' },
  { id: '4', company: 'PearlMed Healthcare', contactPerson: 'Dr. Sneha Patel', email: 'sneha@pearlmed.in', phone: '+91 65432 10987', gstNumber: '06AAECP4567E4Z4', address: '22 Health Avenue', city: 'Pune', country: 'India', postalCode: '411001', paymentTerms: 'Net 30', notes: 'Healthcare sector client', logo: 'PM', documentsCount: 12, status: 'active', revenue: 185000, createdAt: '2024-03-10' },
  { id: '5', company: 'FreshMart Retail', contactPerson: 'Kavya Krishnan', email: 'kavya@freshmart.in', phone: '+91 54321 09876', gstNumber: '33AABCF5678F5Z5', address: '88 Retail Plaza, Anna Nagar', city: 'Chennai', country: 'India', postalCode: '600040', paymentTerms: 'Net 30', notes: 'Retail chain, monthly invoices', logo: 'FM', documentsCount: 28, status: 'active', revenue: 420000, createdAt: '2023-12-05' },
  { id: '6', company: 'ByteForge Technologies', contactPerson: 'Vikram Singh', email: 'vikram@byteforge.io', phone: '+91 43210 98765', gstNumber: '09AABCB6789G6Z6', address: '5 IT Park, Sector 62', city: 'Noida', country: 'India', postalCode: '201309', paymentTerms: 'Net 15', notes: 'Startup, fast growing', logo: 'BF', documentsCount: 9, status: 'active', revenue: 95000, createdAt: '2024-04-22' },
  { id: '7', company: 'Apex Logistics', contactPerson: 'Santhosh Kumar', email: 'santhosh@apexlogistics.com', phone: '+91 32109 87654', gstNumber: '29AACCA7890H7Z7', address: '3 Transport Nagar', city: 'Hyderabad', country: 'India', postalCode: '500003', paymentTerms: 'Net 60', notes: 'Logistics company', logo: 'AL', documentsCount: 16, status: 'inactive', revenue: 210000, createdAt: '2023-09-14' },
  { id: '8', company: 'CreativeWave Agency', contactPerson: 'Meera Joshi', email: 'meera@creativewave.in', phone: '+91 21098 76543', gstNumber: '08AABCC8901I8Z8', address: '14 Creative Hub, Karol Bagh', city: 'Delhi', country: 'India', postalCode: '110005', paymentTerms: 'Net 30', notes: 'Marketing agency', logo: 'CW', documentsCount: 21, status: 'active', revenue: 310000, createdAt: '2024-01-28' },
  { id: '9', company: 'EduSpark Institute', contactPerson: 'Prof. Rajan Gupta', email: 'rajan@eduspark.edu', phone: '+91 10987 65432', gstNumber: '10AABCE9012J9Z9', address: '100 Knowledge Park', city: 'Jaipur', country: 'India', postalCode: '302021', paymentTerms: 'Net 30', notes: 'Educational institution', logo: 'ES', documentsCount: 45, status: 'active', revenue: 520000, createdAt: '2023-08-01' },
  { id: '10', company: 'GreenEarth Farms', contactPerson: 'Anita Desai', email: 'anita@greenearth.farm', phone: '+91 09876 54321', gstNumber: '12AABCG1234K0Z0', address: '22 Agricultural Zone', city: 'Nashik', country: 'India', postalCode: '422001', paymentTerms: 'Net 45', notes: 'Agriculture sector', logo: 'GF', documentsCount: 7, status: 'inactive', revenue: 78000, createdAt: '2024-05-01' },
  { id: '11', company: 'Pinnacle Finance', contactPerson: 'Rahul Verma', email: 'rahul@pinnaclefin.com', phone: '+91 98760 43210', gstNumber: '11AABCP2345L1Z1', address: '18 Financial District', city: 'Mumbai', country: 'India', postalCode: '400051', paymentTerms: 'Net 30', notes: 'NBFC, regular client', logo: 'PF', documentsCount: 33, status: 'active', revenue: 680000, createdAt: '2023-10-12' },
  { id: '12', company: 'NextGen Pharma', contactPerson: 'Dr. Anil Bose', email: 'anil@nextgenpharma.in', phone: '+91 87651 32109', gstNumber: '13AABCN3456M2Z2', address: '5 Pharma Park, Ankleshwar', city: 'Bharuch', country: 'India', postalCode: '393002', paymentTerms: 'Net 30', notes: 'Pharmaceutical company', logo: 'NP', documentsCount: 19, status: 'active', revenue: 295000, createdAt: '2024-02-14' },
  { id: '13', company: 'SwiftCode Systems', contactPerson: 'Pooja Iyer', email: 'pooja@swiftcode.dev', phone: '+91 76540 21098', gstNumber: '32AABCS4567N3Z3', address: '9 Techno Park, Trivandrum', city: 'Thiruvananthapuram', country: 'India', postalCode: '695581', paymentTerms: 'Net 15', notes: 'Software development firm', logo: 'SS', documentsCount: 14, status: 'active', revenue: 190000, createdAt: '2024-03-25' },
  { id: '14', company: 'ArtHouse Studios', contactPerson: 'Nikhil Tiwari', email: 'nikhil@arthouse.in', phone: '+91 65430 10987', gstNumber: '27AABCA5678O4Z4', address: '3 Film City Road', city: 'Mumbai', country: 'India', postalCode: '400063', paymentTerms: 'Net 30', notes: 'Media production house', logo: 'AH', documentsCount: 11, status: 'active', revenue: 145000, createdAt: '2024-04-08' },
  { id: '15', company: 'MegaBuild Corp', contactPerson: 'Suresh Pillai', email: 'suresh@megabuild.co', phone: '+91 54320 09876', gstNumber: '32AABCM6789P5Z5', address: '7 Industrial Estate', city: 'Kochi', country: 'India', postalCode: '682001', paymentTerms: 'Net 60', notes: 'Construction conglomerate', logo: 'MB', documentsCount: 38, status: 'active', revenue: 890000, createdAt: '2023-07-15' },
]

export const DOCUMENTS: Document[] = [
  { id: 'd1', title: 'Invoice #INV-2024-001 - TechNova', type: 'invoice', client: 'TechNova Solutions', status: 'completed', createdAt: '2024-06-01', updatedAt: '2024-06-01', size: '128 KB', pages: 2 },
  { id: 'd2', title: 'Offer Letter - Arjun Sharma', type: 'offer-letter', client: 'TechNova Solutions', status: 'completed', createdAt: '2024-06-02', updatedAt: '2024-06-03', size: '95 KB', pages: 3 },
  { id: 'd3', title: 'Certificate - Web Development Course', type: 'certificates', client: 'EduSpark Institute', status: 'shared', createdAt: '2024-06-03', updatedAt: '2024-06-03', size: '210 KB', pages: 1 },
  { id: 'd4', title: 'Resume - Priya Nair (Senior Dev)', type: 'resume-builder', client: 'GlobalEdge Consulting', status: 'draft', createdAt: '2024-06-04', updatedAt: '2024-06-05', size: '180 KB', pages: 2 },
  { id: 'd5', title: 'Invoice #INV-2024-002 - GlobalEdge', type: 'invoice', client: 'GlobalEdge Consulting', status: 'completed', createdAt: '2024-06-05', updatedAt: '2024-06-05', size: '132 KB', pages: 2 },
  { id: 'd6', title: 'HR Policy - Remote Work Guidelines', type: 'hr-documents', client: 'SkyBuild Infra', status: 'completed', createdAt: '2024-06-06', updatedAt: '2024-06-07', size: '245 KB', pages: 5 },
  { id: 'd7', title: 'Mathematics Question Paper - Class 12', type: 'question-generator', client: 'EduSpark Institute', status: 'completed', createdAt: '2024-06-07', updatedAt: '2024-06-07', size: '156 KB', pages: 4 },
  { id: 'd8', title: 'Experience Letter - Rohan Mehta', type: 'experience-letter', client: 'SkyBuild Infra', status: 'shared', createdAt: '2024-06-08', updatedAt: '2024-06-08', size: '88 KB', pages: 1 },
  { id: 'd9', title: 'Appointment Letter - Kavya K.', type: 'appointment-letter', client: 'FreshMart Retail', status: 'completed', createdAt: '2024-06-09', updatedAt: '2024-06-09', size: '102 KB', pages: 2 },
  { id: 'd10', title: 'Salary Slip - June 2024', type: 'salary-slip', client: 'TechNova Solutions', status: 'completed', createdAt: '2024-06-10', updatedAt: '2024-06-10', size: '78 KB', pages: 1 },
  { id: 'd11', title: 'Invoice #INV-2024-003 - FreshMart', type: 'invoice', client: 'FreshMart Retail', status: 'draft', createdAt: '2024-06-11', updatedAt: '2024-06-12', size: '140 KB', pages: 2 },
  { id: 'd12', title: 'ID Card - Employee Batch 2024', type: 'id-card', client: 'ByteForge Technologies', status: 'completed', createdAt: '2024-06-12', updatedAt: '2024-06-12', size: '320 KB', pages: 5 },
  { id: 'd13', title: 'Certificate - Data Science Program', type: 'certificates', client: 'EduSpark Institute', status: 'completed', createdAt: '2024-06-13', updatedAt: '2024-06-13', size: '215 KB', pages: 1 },
  { id: 'd14', title: 'Offer Letter - Vikram Singh (PM)', type: 'offer-letter', client: 'ByteForge Technologies', status: 'shared', createdAt: '2024-06-14', updatedAt: '2024-06-14', size: '98 KB', pages: 3 },
  { id: 'd15', title: 'Resume Analyzer - Santhosh K.', type: 'resume-analyzer', client: 'Apex Logistics', status: 'archived', createdAt: '2024-05-20', updatedAt: '2024-05-21', size: '165 KB', pages: 2 },
  { id: 'd16', title: 'Invoice #INV-2024-004 - Pinnacle', type: 'invoice', client: 'Pinnacle Finance', status: 'completed', createdAt: '2024-06-15', updatedAt: '2024-06-15', size: '128 KB', pages: 2 },
  { id: 'd17', title: 'Science Question Paper - Grade 10', type: 'question-generator', client: 'EduSpark Institute', status: 'draft', createdAt: '2024-06-16', updatedAt: '2024-06-16', size: '178 KB', pages: 4 },
  { id: 'd18', title: 'HR Policy - Leave Management', type: 'hr-documents', client: 'Pinnacle Finance', status: 'completed', createdAt: '2024-06-17', updatedAt: '2024-06-18', size: '235 KB', pages: 6 },
  { id: 'd19', title: 'Salary Slip - June 2024 (Bulk)', type: 'salary-slip', client: 'CreativeWave Agency', status: 'completed', createdAt: '2024-06-18', updatedAt: '2024-06-18', size: '450 KB', pages: 12 },
  { id: 'd20', title: 'Appointment Letter - Dr. Bose', type: 'appointment-letter', client: 'NextGen Pharma', status: 'completed', createdAt: '2024-06-19', updatedAt: '2024-06-19', size: '105 KB', pages: 2 },
]

export const TEMPLATES: Template[] = [
  { id: 't1', name: 'Professional Invoice A4', type: 'invoice', description: 'Clean GST invoice with product table and payment terms', preview: '/templates/invoice-1.jpg', usageCount: 243, isFavorite: true, tags: ['GST', 'Professional', 'Popular'] },
  { id: 't2', name: 'Modern Invoice Dark', type: 'invoice', description: 'Dark themed premium invoice for tech companies', preview: '/templates/invoice-2.jpg', usageCount: 128, isFavorite: false, tags: ['Dark', 'Tech', 'Modern'] },
  { id: 't3', name: 'Minimal Invoice', type: 'invoice', description: 'Ultra minimal single page invoice template', preview: '/templates/invoice-3.jpg', usageCount: 312, isFavorite: true, tags: ['Minimal', 'Clean', 'Popular'] },
  { id: 't4', name: 'Corporate Offer Letter', type: 'offer-letter', description: 'Formal offer letter with all standard clauses', preview: '/templates/offer-1.jpg', usageCount: 189, isFavorite: true, tags: ['Corporate', 'Formal', 'Complete'] },
  { id: 't5', name: 'Startup Offer Letter', type: 'offer-letter', description: 'Friendly and concise offer letter for startups', preview: '/templates/offer-2.jpg', usageCount: 94, isFavorite: false, tags: ['Startup', 'Friendly', 'ESOP'] },
  { id: 't6', name: 'Senior Management Offer', type: 'offer-letter', description: 'Comprehensive offer letter for senior executives', preview: '/templates/offer-3.jpg', usageCount: 67, isFavorite: false, tags: ['Senior', 'Executive', 'Detailed'] },
  { id: 't7', name: 'Employee Warning Letter', type: 'hr-documents', description: 'Formal warning letter with disciplinary details', preview: '/templates/hr-1.jpg', usageCount: 45, isFavorite: false, tags: ['Disciplinary', 'HR', 'Formal'] },
  { id: 't8', name: 'Relieving Letter', type: 'hr-documents', description: 'Standard relieving letter for resigned employees', preview: '/templates/hr-2.jpg', usageCount: 156, isFavorite: true, tags: ['Relieving', 'Exit', 'Standard'] },
  { id: 't9', name: 'Certificate of Completion', type: 'certificates', description: 'Elegant certificate for course completion', preview: '/templates/cert-1.jpg', usageCount: 278, isFavorite: true, tags: ['Course', 'Academic', 'Elegant'] },
  { id: 't10', name: 'Achievement Certificate', type: 'certificates', description: 'Premium certificate for awards and achievements', preview: '/templates/cert-2.jpg', usageCount: 193, isFavorite: false, tags: ['Award', 'Premium', 'Achievement'] },
  { id: 't11', name: 'Participation Certificate', type: 'certificates', description: 'Simple participation certificate for events', preview: '/templates/cert-3.jpg', usageCount: 341, isFavorite: true, tags: ['Event', 'Participation', 'Simple'] },
  { id: 't12', name: 'ATS Resume Classic', type: 'resume-builder', description: 'Clean ATS-optimized resume for all industries', preview: '/templates/resume-1.jpg', usageCount: 521, isFavorite: true, tags: ['ATS', 'Classic', 'Popular'] },
  { id: 't13', name: 'Creative Resume', type: 'resume-builder', description: 'Eye-catching creative resume for design roles', preview: '/templates/resume-2.jpg', usageCount: 234, isFavorite: false, tags: ['Creative', 'Design', 'Visual'] },
  { id: 't14', name: 'Tech Resume', type: 'resume-builder', description: 'Developer-focused resume with skills emphasis', preview: '/templates/resume-3.jpg', usageCount: 456, isFavorite: true, tags: ['Tech', 'Developer', 'Skills'] },
  { id: 't15', name: 'MCQ Question Paper', type: 'question-generator', description: 'Multiple choice question paper template', preview: '/templates/qp-1.jpg', usageCount: 178, isFavorite: false, tags: ['MCQ', 'Objective', 'Standard'] },
  { id: 't16', name: 'Theory Question Paper', type: 'question-generator', description: 'Descriptive question paper with section markers', preview: '/templates/qp-2.jpg', usageCount: 145, isFavorite: true, tags: ['Theory', 'Descriptive', 'Academic'] },
  { id: 't17', name: 'Corporate ID Card', type: 'id-card', description: 'Professional corporate ID card with RFID space', preview: '/templates/id-1.jpg', usageCount: 89, isFavorite: false, tags: ['Corporate', 'RFID', 'Professional'] },
  { id: 't18', name: 'Experience Letter Standard', type: 'experience-letter', description: 'Standard experience letter format', preview: '/templates/exp-1.jpg', usageCount: 213, isFavorite: true, tags: ['Standard', 'HR', 'Experience'] },
  { id: 't19', name: 'Pay Slip Detailed', type: 'salary-slip', description: 'Comprehensive pay slip with all components', preview: '/templates/salary-1.jpg', usageCount: 167, isFavorite: false, tags: ['Payroll', 'Detailed', 'Tax'] },
  { id: 't20', name: 'Appointment Standard', type: 'appointment-letter', description: 'Standard appointment letter for new joiners', preview: '/templates/apt-1.jpg', usageCount: 134, isFavorite: false, tags: ['Appointment', 'Joining', 'HR'] },
]

export const ACTIVITIES: ActivityItem[] = [
  { id: 'a1', action: 'Created invoice', document: 'INV-2024-001', client: 'TechNova Solutions', time: '2 min ago', type: 'create' },
  { id: 'a2', action: 'Downloaded', document: 'Offer Letter - Arjun Sharma', client: 'TechNova Solutions', time: '15 min ago', type: 'download' },
  { id: 'a3', action: 'Shared certificate', document: 'Web Dev Certificate', client: 'EduSpark Institute', time: '1 hour ago', type: 'share' },
  { id: 'a4', action: 'Edited draft', document: 'Resume - Priya Nair', client: 'GlobalEdge Consulting', time: '2 hours ago', type: 'edit' },
  { id: 'a5', action: 'Generated document', document: 'HR Policy', client: 'SkyBuild Infra', time: '3 hours ago', type: 'create' },
  { id: 'a6', action: 'Downloaded', document: 'Question Paper - Maths', client: 'EduSpark Institute', time: '5 hours ago', type: 'download' },
  { id: 'a7', action: 'Archived', document: 'Resume Analyzer', client: 'Apex Logistics', time: 'Yesterday', type: 'delete' },
  { id: 'a8', action: 'Created invoice', document: 'INV-2024-002', client: 'GlobalEdge Consulting', time: 'Yesterday', type: 'create' },
]

export const NOTIFICATIONS: Notification[] = [
  { id: 'n1', title: 'Document Generated', message: 'Invoice INV-2024-001 has been generated successfully', time: '2 min ago', read: false, type: 'success' },
  { id: 'n2', title: 'Template Updated', message: 'ATS Resume Classic template has been updated', time: '1 hour ago', read: false, type: 'info' },
  { id: 'n3', title: 'New Client Added', message: 'MegaBuild Corp has been added to your clients', time: '3 hours ago', read: true, type: 'info' },
  { id: 'n4', title: 'Storage Alert', message: 'You have used 80% of your storage quota', time: 'Yesterday', read: false, type: 'warning' },
  { id: 'n5', title: 'Export Complete', message: 'Bulk salary slips export is ready for download', time: 'Yesterday', read: true, type: 'success' },
]

export const CHART_DATA = {
  monthly: [
    { month: 'Jan', documents: 42, revenue: 128000 },
    { month: 'Feb', documents: 58, revenue: 156000 },
    { month: 'Mar', documents: 49, revenue: 142000 },
    { month: 'Apr', documents: 71, revenue: 198000 },
    { month: 'May', documents: 85, revenue: 241000 },
    { month: 'Jun', documents: 94, revenue: 287000 },
    { month: 'Jul', documents: 78, revenue: 215000 },
    { month: 'Aug', documents: 102, revenue: 312000 },
    { month: 'Sep', documents: 89, revenue: 268000 },
    { month: 'Oct', documents: 115, revenue: 356000 },
    { month: 'Nov', documents: 128, revenue: 398000 },
    { month: 'Dec', documents: 143, revenue: 445000 },
  ],
  docTypes: [
    { name: 'Invoice', value: 35, color: '#2563EB' },
    { name: 'Offer Letter', value: 18, color: '#059669' },
    { name: 'HR Docs', value: 14, color: '#7C3AED' },
    { name: 'Certificates', value: 15, color: '#DC2626' },
    { name: 'Resume', value: 10, color: '#0891B2' },
    { name: 'Others', value: 8, color: '#D97706' },
  ],
  clientGrowth: [
    { month: 'Jan', clients: 8 },
    { month: 'Feb', clients: 11 },
    { month: 'Mar', clients: 14 },
    { month: 'Apr', clients: 18 },
    { month: 'May', clients: 22 },
    { month: 'Jun', clients: 25 },
  ],
}
